### ISSUE TITLE
happyday

### ISSUE THREAD

**Issue by maravento** [kinomakino/ransomware_file_extensions#3]
great work. 
by the way. Missing ransomware extensions: *.happyday* (.happydayzz and .happydayzzz)

**Comment by maravento** [comment]
thanks

**Comment by kinomakino** [comment]
Muchas gracias!!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by maravento** [comment]
Hi. Add ransomware wannacry:
*.wcry (done)
*.WNCRY
*.wncry
*.wncryt
*.wnry
